services:
  postgis:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    container_name: postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carto
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d carto"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  martin:
    image: maplibre/martin:v0.8.0
    platform: linux/amd64
    container_name: martin
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:password@postgis:5432/carto

volumes:
  postgis-data: